name: Update documentation

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.10"
      - name: Setup Just
        uses: extractions/setup-just@v3
      - name: Install uv and set the Python version
        uses: astral-sh/setup-uv@v7
        with:
          python-version: "3.10"
      - name: Install the project
        run: uv sync --all-extras --dev
      - name: Build
        run: just docs-build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./site
